/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ATS_YogaIrgi_35_XIIRPLB;

import javax.swing.JOptionPane;
/**
 *
 * @author Asus
 */
public class Kakulator_bangundatar extends javax.swing.JFrame {

    /** Creates new form Kakulator_bangundatar */
    public Kakulator_bangundatar() {
        initComponents();
        // menhilangkan text tentang bangun persegi
        jLabel15.setVisible(false);
        jLabel16.setVisible(false);
        jLabel17.setVisible(false);
        jLabel18.setVisible(false);
        jLabel11.setVisible(false);
       
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelSidebar = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Bmenu = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        Bhome = new javax.swing.JButton();
        PanelContainer = new javax.swing.JPanel();
        PanelJajarGenjang = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        tinggi = new javax.swing.JTextField();
        btnkelilingjajar = new javax.swing.JButton();
        outputjajar = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        btnluasjajar = new javax.swing.JButton();
        jLabel33 = new javax.swing.JLabel();
        alas = new javax.swing.JTextField();
        btnbackjajar = new javax.swing.JButton();
        PanelSegitiga = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        B = new javax.swing.JTextField();
        btnkelilingsegi = new javax.swing.JButton();
        outputsegitiga = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        btnluassegi = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        A = new javax.swing.JTextField();
        btnbacksegi = new javax.swing.JButton();
        PanelLingkaran = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnkelling = new javax.swing.JButton();
        outputling = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        btnluasling = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        jari2 = new javax.swing.JTextField();
        btnbackling = new javax.swing.JButton();
        PanelPersegi = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        sisi = new javax.swing.JTextField();
        bcleae = new javax.swing.JButton();
        bkeliling = new javax.swing.JButton();
        output = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        bluas = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        Bback = new javax.swing.JButton();
        PanelMenu = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        Menupersegi = new javax.swing.JButton();
        menupersegipanjang = new javax.swing.JButton();
        Menulingkaran = new javax.swing.JButton();
        Menusegitiga = new javax.swing.JButton();
        Menujajargenjang = new javax.swing.JButton();
        Menubelahketupat = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        PanelHome = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        PanelPersegiPanjang = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        l = new javax.swing.JTextField();
        btnkeliling = new javax.swing.JButton();
        outputtext = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        btnluas = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        p = new javax.swing.JTextField();
        btnback = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelSidebar.setBackground(new java.awt.Color(7, 7, 7));

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ATS_YogaIrgi_35_XIIRPLB/icon/kakulator.png"))); // NOI18N
        jLabel3.setText("Kakulator");

        Bmenu.setBackground(new java.awt.Color(42, 42, 42));
        Bmenu.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        Bmenu.setForeground(new java.awt.Color(255, 255, 255));
        Bmenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ATS_YogaIrgi_35_XIIRPLB/icon/menu.png"))); // NOI18N
        Bmenu.setText("Menu");
        Bmenu.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        Bmenu.setIconTextGap(25);
        Bmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BmenuActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 0, 0));
        jButton3.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ATS_YogaIrgi_35_XIIRPLB/icon/logout.png"))); // NOI18N
        jButton3.setText("Keluar");
        jButton3.setHideActionText(true);
        jButton3.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        jButton3.setIconTextGap(25);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        Bhome.setBackground(new java.awt.Color(42, 42, 42));
        Bhome.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        Bhome.setForeground(new java.awt.Color(255, 255, 255));
        Bhome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ATS_YogaIrgi_35_XIIRPLB/icon/home.png"))); // NOI18N
        Bhome.setText("Home");
        Bhome.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        Bhome.setIconTextGap(25);
        Bhome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BhomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelSidebarLayout = new javax.swing.GroupLayout(PanelSidebar);
        PanelSidebar.setLayout(PanelSidebarLayout);
        PanelSidebarLayout.setHorizontalGroup(
            PanelSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSidebarLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel3)
                .addContainerGap(35, Short.MAX_VALUE))
            .addComponent(Bmenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Bhome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PanelSidebarLayout.setVerticalGroup(
            PanelSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSidebarLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel3)
                .addGap(78, 78, 78)
                .addComponent(Bhome, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Bmenu, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 645, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        PanelContainer.setBackground(new java.awt.Color(244, 244, 244));

        PanelJajarGenjang.setBackground(new java.awt.Color(244, 244, 244));

        jLabel30.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(38, 67, 135));
        jLabel30.setText("Jajar Genjang");

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        tinggi.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N

        btnkelilingjajar.setBackground(new java.awt.Color(24, 67, 47));
        btnkelilingjajar.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnkelilingjajar.setForeground(new java.awt.Color(244, 244, 244));
        btnkelilingjajar.setText("Keliling");
        btnkelilingjajar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkelilingjajarActionPerformed(evt);
            }
        });

        outputjajar.setBackground(new java.awt.Color(42, 42, 42));
        outputjajar.setFont(new java.awt.Font("Verdana", 1, 50)); // NOI18N
        outputjajar.setForeground(new java.awt.Color(42, 42, 42));
        outputjajar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        outputjajar.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.black, java.awt.Color.black));
        outputjajar.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        jLabel31.setBackground(new java.awt.Color(42, 42, 42));
        jLabel31.setFont(new java.awt.Font("Verdana", 1, 35)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(42, 42, 42));
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setText("Hasil");
        jLabel31.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.black, java.awt.Color.black));

        jLabel32.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(42, 42, 42));
        jLabel32.setText("Masukan Nilai Tinggi");

        btnluasjajar.setBackground(new java.awt.Color(38, 67, 135));
        btnluasjajar.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnluasjajar.setForeground(new java.awt.Color(244, 244, 244));
        btnluasjajar.setText("Luas");
        btnluasjajar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnluasjajarActionPerformed(evt);
            }
        });

        jLabel33.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(42, 42, 42));
        jLabel33.setText("Masukan Nilai Alas");

        alas.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tinggi)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(outputjajar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(alas)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel32)
                            .addComponent(jLabel33))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(btnkelilingjajar, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnluasjajar, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jLabel33)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(alas, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel32)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tinggi, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnkelilingjajar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnluasjajar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(outputjajar, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        btnbackjajar.setBackground(new java.awt.Color(38, 67, 135));
        btnbackjajar.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnbackjajar.setForeground(new java.awt.Color(244, 244, 244));
        btnbackjajar.setText("Back");
        btnbackjajar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackjajarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelJajarGenjangLayout = new javax.swing.GroupLayout(PanelJajarGenjang);
        PanelJajarGenjang.setLayout(PanelJajarGenjangLayout);
        PanelJajarGenjangLayout.setHorizontalGroup(
            PanelJajarGenjangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelJajarGenjangLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelJajarGenjangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnbackjajar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(PanelJajarGenjangLayout.createSequentialGroup()
                .addGap(223, 223, 223)
                .addComponent(jLabel30)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelJajarGenjangLayout.setVerticalGroup(
            PanelJajarGenjangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelJajarGenjangLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel30)
                .addGap(70, 70, 70)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btnbackjajar, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(226, Short.MAX_VALUE))
        );

        PanelSegitiga.setBackground(new java.awt.Color(244, 244, 244));

        jLabel25.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(24, 67, 47));
        jLabel25.setText("Segitiga Liku - Liku");

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        B.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N

        btnkelilingsegi.setBackground(new java.awt.Color(24, 67, 47));
        btnkelilingsegi.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnkelilingsegi.setForeground(new java.awt.Color(244, 244, 244));
        btnkelilingsegi.setText("Keliling");
        btnkelilingsegi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkelilingsegiActionPerformed(evt);
            }
        });

        outputsegitiga.setBackground(new java.awt.Color(42, 42, 42));
        outputsegitiga.setFont(new java.awt.Font("Verdana", 1, 50)); // NOI18N
        outputsegitiga.setForeground(new java.awt.Color(42, 42, 42));
        outputsegitiga.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        outputsegitiga.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.black, java.awt.Color.black));
        outputsegitiga.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        jLabel27.setBackground(new java.awt.Color(42, 42, 42));
        jLabel27.setFont(new java.awt.Font("Verdana", 1, 35)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(42, 42, 42));
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("Hasil");
        jLabel27.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.black, java.awt.Color.black));

        jLabel28.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(42, 42, 42));
        jLabel28.setText("Masukan Nilai B");

        btnluassegi.setBackground(new java.awt.Color(38, 67, 135));
        btnluassegi.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnluassegi.setForeground(new java.awt.Color(244, 244, 244));
        btnluassegi.setText("Luas");
        btnluassegi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnluassegiActionPerformed(evt);
            }
        });

        jLabel29.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(42, 42, 42));
        jLabel29.setText("Masukan Nilai A");

        A.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(B)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(outputsegitiga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(A)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel28)
                            .addComponent(jLabel29))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(btnkelilingsegi, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnluassegi, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jLabel29)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(A, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(B, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnkelilingsegi, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnluassegi, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(outputsegitiga, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        btnbacksegi.setBackground(new java.awt.Color(24, 67, 47));
        btnbacksegi.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnbacksegi.setForeground(new java.awt.Color(244, 244, 244));
        btnbacksegi.setText("Back");
        btnbacksegi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbacksegiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelSegitigaLayout = new javax.swing.GroupLayout(PanelSegitiga);
        PanelSegitiga.setLayout(PanelSegitigaLayout);
        PanelSegitigaLayout.setHorizontalGroup(
            PanelSegitigaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSegitigaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelSegitigaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnbacksegi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(PanelSegitigaLayout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addComponent(jLabel25)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelSegitigaLayout.setVerticalGroup(
            PanelSegitigaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSegitigaLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel25)
                .addGap(66, 66, 66)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btnbacksegi, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(226, Short.MAX_VALUE))
        );

        PanelLingkaran.setBackground(new java.awt.Color(244, 244, 244));

        jLabel23.setBackground(new java.awt.Color(34, 34, 34));
        jLabel23.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(34, 34, 34));
        jLabel23.setText("Lingkaran");

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        btnkelling.setBackground(new java.awt.Color(24, 67, 47));
        btnkelling.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnkelling.setForeground(new java.awt.Color(244, 244, 244));
        btnkelling.setText("Keliling");
        btnkelling.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkellingActionPerformed(evt);
            }
        });

        outputling.setBackground(new java.awt.Color(42, 42, 42));
        outputling.setFont(new java.awt.Font("Verdana", 1, 50)); // NOI18N
        outputling.setForeground(new java.awt.Color(42, 42, 42));
        outputling.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        outputling.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.black, java.awt.Color.black));
        outputling.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        jLabel24.setBackground(new java.awt.Color(42, 42, 42));
        jLabel24.setFont(new java.awt.Font("Verdana", 1, 35)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(42, 42, 42));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("Hasil");
        jLabel24.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.black, java.awt.Color.black));

        btnluasling.setBackground(new java.awt.Color(38, 67, 135));
        btnluasling.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnluasling.setForeground(new java.awt.Color(244, 244, 244));
        btnluasling.setText("Luas");
        btnluasling.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnluaslingActionPerformed(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(42, 42, 42));
        jLabel26.setText("Masukan Nilai Jari-Jari");

        jari2.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jari2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jari2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(outputling, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jari2)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addGap(0, 465, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btnkelling, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnluasling, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jari2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnkelling, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnluasling, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(outputling, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(107, 107, 107))
        );

        btnbackling.setBackground(new java.awt.Color(34, 34, 34));
        btnbackling.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnbackling.setForeground(new java.awt.Color(244, 244, 244));
        btnbackling.setText("Back");
        btnbackling.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbacklingActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelLingkaranLayout = new javax.swing.GroupLayout(PanelLingkaran);
        PanelLingkaran.setLayout(PanelLingkaranLayout);
        PanelLingkaranLayout.setHorizontalGroup(
            PanelLingkaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLingkaranLayout.createSequentialGroup()
                .addGap(259, 259, 259)
                .addComponent(jLabel23)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(PanelLingkaranLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelLingkaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnbackling, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        PanelLingkaranLayout.setVerticalGroup(
            PanelLingkaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLingkaranLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel23)
                .addGap(68, 68, 68)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addComponent(btnbackling, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(284, Short.MAX_VALUE))
        );

        PanelPersegi.setBackground(new java.awt.Color(244, 244, 244));
        PanelPersegi.setPreferredSize(new java.awt.Dimension(731, 991));

        jLabel10.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(247, 141, 17));
        jLabel10.setText("Bangun Datar Persegi");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        sisi.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N

        bcleae.setBackground(new java.awt.Color(190, 32, 42));
        bcleae.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        bcleae.setForeground(new java.awt.Color(244, 244, 244));
        bcleae.setText("Clear");
        bcleae.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcleaeActionPerformed(evt);
            }
        });

        bkeliling.setBackground(new java.awt.Color(24, 67, 47));
        bkeliling.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        bkeliling.setForeground(new java.awt.Color(244, 244, 244));
        bkeliling.setText("Keliling");
        bkeliling.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bkelilingActionPerformed(evt);
            }
        });

        output.setBackground(new java.awt.Color(42, 42, 42));
        output.setFont(new java.awt.Font("Verdana", 1, 50)); // NOI18N
        output.setForeground(new java.awt.Color(42, 42, 42));
        output.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        output.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.black, java.awt.Color.black));
        output.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        jLabel13.setBackground(new java.awt.Color(42, 42, 42));
        jLabel13.setFont(new java.awt.Font("Verdana", 1, 35)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(42, 42, 42));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Hasil");
        jLabel13.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.black, java.awt.Color.black));

        jLabel14.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(42, 42, 42));
        jLabel14.setText("Masukan Nilai Sisi ");

        bluas.setBackground(new java.awt.Color(38, 67, 135));
        bluas.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        bluas.setForeground(new java.awt.Color(244, 244, 244));
        bluas.setText("Luas");
        bluas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bluasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sisi)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                            .addComponent(bcleae, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(bkeliling, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bluas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(output, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jLabel14))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sisi, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bcleae, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bkeliling, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bluas, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(output, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(247, 141, 17));
        jLabel11.setText("Luas Persegi = sisi × sisi");

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel15.setText("Persegi adalah bangun datar dua dimensi  yang memiliki keempat sisi dengan panjang");

        jLabel16.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel16.setText("yang sama dan keempat sudutnya membentuk sudut siku-siku.");

        jLabel17.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(247, 141, 17));
        jLabel17.setText("Rumus Luas & Keliling Persegi");

        jLabel18.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(247, 141, 17));
        jLabel18.setText("Keliling Persegi = 4 × sisi");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(jLabel11)
                    .addComponent(jLabel18))
                .addContainerGap(118, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addGap(24, 24, 24))
        );

        Bback.setBackground(new java.awt.Color(247, 141, 17));
        Bback.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        Bback.setForeground(new java.awt.Color(244, 244, 244));
        Bback.setText("Back");
        Bback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BbackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelPersegiLayout = new javax.swing.GroupLayout(PanelPersegi);
        PanelPersegi.setLayout(PanelPersegiLayout);
        PanelPersegiLayout.setHorizontalGroup(
            PanelPersegiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Bback, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(PanelPersegiLayout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelPersegiLayout.setVerticalGroup(
            PanelPersegiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPersegiLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel10)
                .addGap(53, 53, 53)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(Bback, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(93, Short.MAX_VALUE))
        );

        PanelMenu.setBackground(new java.awt.Color(248, 249, 252));
        PanelMenu.setName("Kakulator Bangun Datar - gayoga\n"); // NOI18N

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabel6.setText("Menu Bangun Datar");

        Menupersegi.setBackground(new java.awt.Color(247, 141, 17));
        Menupersegi.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        Menupersegi.setForeground(new java.awt.Color(255, 255, 255));
        Menupersegi.setText("Persegi");
        Menupersegi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenupersegiActionPerformed(evt);
            }
        });

        menupersegipanjang.setBackground(new java.awt.Color(190, 32, 42));
        menupersegipanjang.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        menupersegipanjang.setForeground(new java.awt.Color(255, 255, 255));
        menupersegipanjang.setText("Persegi Panjang");
        menupersegipanjang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menupersegipanjangActionPerformed(evt);
            }
        });

        Menulingkaran.setBackground(new java.awt.Color(34, 34, 34));
        Menulingkaran.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        Menulingkaran.setForeground(new java.awt.Color(255, 255, 255));
        Menulingkaran.setText("Lingkaran");
        Menulingkaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenulingkaranActionPerformed(evt);
            }
        });

        Menusegitiga.setBackground(new java.awt.Color(24, 67, 47));
        Menusegitiga.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        Menusegitiga.setForeground(new java.awt.Color(255, 255, 255));
        Menusegitiga.setText("Segitiga");
        Menusegitiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenusegitigaActionPerformed(evt);
            }
        });

        Menujajargenjang.setBackground(new java.awt.Color(38, 67, 135));
        Menujajargenjang.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        Menujajargenjang.setForeground(new java.awt.Color(255, 255, 255));
        Menujajargenjang.setText("Jajar Genjang");
        Menujajargenjang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenujajargenjangActionPerformed(evt);
            }
        });

        Menubelahketupat.setBackground(new java.awt.Color(212, 183, 249));
        Menubelahketupat.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        Menubelahketupat.setForeground(new java.awt.Color(255, 255, 255));
        Menubelahketupat.setText("Belah Ketupat");
        Menubelahketupat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenubelahketupatActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel7.setText("____________________________________________");

        jLabel8.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel8.setText("Pilih menu bangun datar yang Anda ingin jalankan.");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ATS_YogaIrgi_35_XIIRPLB/icon/pattern.png"))); // NOI18N

        javax.swing.GroupLayout PanelMenuLayout = new javax.swing.GroupLayout(PanelMenu);
        PanelMenu.setLayout(PanelMenuLayout);
        PanelMenuLayout.setHorizontalGroup(
            PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMenuLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addGroup(PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(PanelMenuLayout.createSequentialGroup()
                            .addComponent(Menujajargenjang, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(Menubelahketupat, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE))
                        .addComponent(jLabel6)
                        .addGroup(PanelMenuLayout.createSequentialGroup()
                            .addGroup(PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(Menulingkaran, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
                                .addComponent(Menupersegi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(18, 18, 18)
                            .addGroup(PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(menupersegipanjang, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
                                .addComponent(Menusegitiga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 767, Short.MAX_VALUE)
        );
        PanelMenuLayout.setVerticalGroup(
            PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMenuLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addGap(24, 24, 24)
                .addComponent(jLabel8)
                .addGap(32, 32, 32)
                .addGroup(PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(menupersegipanjang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Menupersegi, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Menusegitiga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Menulingkaran, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Menubelahketupat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Menujajargenjang, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PanelHome.setBackground(new java.awt.Color(244, 244, 244));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabel1.setText("Di Kakulator Bangun Datar");

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel2.setText("\"Mari menghitung dengan senyum di wajah\"");

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabel4.setText("Selamat Datang");

        jButton1.setBackground(new java.awt.Color(7, 7, 7));
        jButton1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Let's Gooww");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ATS_YogaIrgi_35_XIIRPLB/icon/bghome.png"))); // NOI18N

        javax.swing.GroupLayout PanelHomeLayout = new javax.swing.GroupLayout(PanelHome);
        PanelHome.setLayout(PanelHomeLayout);
        PanelHomeLayout.setHorizontalGroup(
            PanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelHomeLayout.createSequentialGroup()
                .addGroup(PanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelHomeLayout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(jLabel2))
                    .addGroup(PanelHomeLayout.createSequentialGroup()
                        .addGap(265, 265, 265)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 767, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelHomeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelHomeLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(93, 93, 93))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelHomeLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(214, 214, 214))))
        );
        PanelHomeLayout.setVerticalGroup(
            PanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelHomeLayout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(48, 48, 48)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 574, Short.MAX_VALUE))
        );

        PanelPersegiPanjang.setBackground(new java.awt.Color(244, 244, 244));

        jLabel21.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(190, 32, 42));
        jLabel21.setText("Persegi Panjang");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        l.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N

        btnkeliling.setBackground(new java.awt.Color(24, 67, 47));
        btnkeliling.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnkeliling.setForeground(new java.awt.Color(244, 244, 244));
        btnkeliling.setText("Keliling");
        btnkeliling.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkelilingActionPerformed(evt);
            }
        });

        outputtext.setBackground(new java.awt.Color(42, 42, 42));
        outputtext.setFont(new java.awt.Font("Verdana", 1, 50)); // NOI18N
        outputtext.setForeground(new java.awt.Color(42, 42, 42));
        outputtext.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        outputtext.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.black, java.awt.Color.black));
        outputtext.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        jLabel19.setBackground(new java.awt.Color(42, 42, 42));
        jLabel19.setFont(new java.awt.Font("Verdana", 1, 35)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(42, 42, 42));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Hasil");
        jLabel19.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.black, java.awt.Color.black));

        jLabel20.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(42, 42, 42));
        jLabel20.setText("Masukan Nilai Sisi Lebar");

        btnluas.setBackground(new java.awt.Color(38, 67, 135));
        btnluas.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnluas.setForeground(new java.awt.Color(244, 244, 244));
        btnluas.setText("Luas");
        btnluas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnluasActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(42, 42, 42));
        jLabel22.setText("Masukan Nilai Panjang");

        p.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(outputtext, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(p)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(jLabel22))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnkeliling, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnluas, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(p, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(l, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnkeliling, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnluas, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(outputtext, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        btnback.setBackground(new java.awt.Color(190, 32, 42));
        btnback.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnback.setForeground(new java.awt.Color(244, 244, 244));
        btnback.setText("Back");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelPersegiPanjangLayout = new javax.swing.GroupLayout(PanelPersegiPanjang);
        PanelPersegiPanjang.setLayout(PanelPersegiPanjangLayout);
        PanelPersegiPanjangLayout.setHorizontalGroup(
            PanelPersegiPanjangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPersegiPanjangLayout.createSequentialGroup()
                .addGap(212, 212, 212)
                .addComponent(jLabel21)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(PanelPersegiPanjangLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelPersegiPanjangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnback, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        PanelPersegiPanjangLayout.setVerticalGroup(
            PanelPersegiPanjangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPersegiPanjangLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel21)
                .addGap(70, 70, 70)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btnback, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(250, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PanelContainerLayout = new javax.swing.GroupLayout(PanelContainer);
        PanelContainer.setLayout(PanelContainerLayout);
        PanelContainerLayout.setHorizontalGroup(
            PanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(PanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(PanelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(PanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(PanelPersegi, javax.swing.GroupLayout.DEFAULT_SIZE, 767, Short.MAX_VALUE))
            .addGroup(PanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(PanelPersegiPanjang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(PanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelContainerLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(PanelLingkaran, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(PanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelContainerLayout.createSequentialGroup()
                    .addGap(12, 12, 12)
                    .addComponent(PanelSegitiga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(12, 12, 12)))
            .addGroup(PanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelContainerLayout.createSequentialGroup()
                    .addGap(12, 12, 12)
                    .addComponent(PanelJajarGenjang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(12, 12, 12)))
        );
        PanelContainerLayout.setVerticalGroup(
            PanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(PanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(PanelMenu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(PanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(PanelPersegi, javax.swing.GroupLayout.DEFAULT_SIZE, 1020, Short.MAX_VALUE))
            .addGroup(PanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(PanelPersegiPanjang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(PanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelContainerLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(PanelLingkaran, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(PanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelContainerLayout.createSequentialGroup()
                    .addGap(12, 12, 12)
                    .addComponent(PanelSegitiga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(12, 12, 12)))
            .addGroup(PanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelContainerLayout.createSequentialGroup()
                    .addGap(12, 12, 12)
                    .addComponent(PanelJajarGenjang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(12, 12, 12)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelSidebar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelSidebar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(PanelContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
        int panjang1, lebar1, luaspp, kelilingpp, jari1, kelilinglingkaran, luaslingkaran;
        int nilaia, nilaib, luassegi, kelilingsegi;
        int alas1, tinggi1, luasjajar, kelilingjajar;
    
    private void BhomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BhomeActionPerformed
        // TODO add your handling code here:
        PanelContainer.removeAll();
        PanelContainer.repaint();
        PanelContainer.revalidate();
        
        PanelContainer.add(PanelHome);
        PanelContainer.repaint();
        PanelContainer.revalidate();
    }//GEN-LAST:event_BhomeActionPerformed

    private void BmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BmenuActionPerformed
        // TODO add your handling code here:
        PanelContainer.removeAll();
        PanelContainer.repaint();
        PanelContainer.revalidate();
        
        PanelContainer.add(PanelMenu);
        PanelContainer.repaint();
        PanelContainer.revalidate();
    }//GEN-LAST:event_BmenuActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        // Ketika pengguna ingin logout
        int selectedOption = JOptionPane.showConfirmDialog(null, "Apakah Anda yakin ingin keluar?", "Konfirmasi Keluar", JOptionPane.YES_NO_OPTION);
        if (selectedOption == JOptionPane.YES_OPTION){
        dispose();
        }else {
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void bkelilingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bkelilingActionPerformed
        // TODO add your handling code here:
        sisipersegi = Integer.parseInt(sisi.getText());
        keliling = 4 * sisipersegi;
        String kelilingpersegi = Integer.toString(keliling);
        
        output.setText(kelilingpersegi);
        jLabel15.setVisible(true);
        jLabel16.setVisible(true);
        jLabel17.setVisible(true);
        jLabel18.setVisible(true);
        jLabel11.setVisible(true);
    }//GEN-LAST:event_bkelilingActionPerformed

    // membuat variabel untuk menampung inputan
    int sisipersegi, luas, keliling;
    private void BbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BbackActionPerformed
        // TODO add your handling code here:
        PanelContainer.removeAll();
        PanelContainer.repaint();
        PanelContainer.revalidate();
        
        PanelContainer.add(PanelMenu);
        PanelContainer.repaint();
        PanelContainer.revalidate();
    }//GEN-LAST:event_BbackActionPerformed

    private void bcleaeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcleaeActionPerformed
        // TODO add your handling code here:
        sisi.setText("");
        output.setText("");
        jLabel15.setVisible(false);
        jLabel16.setVisible(false);
        jLabel17.setVisible(false);
        jLabel18.setVisible(false);
        jLabel11.setVisible(false);
    }//GEN-LAST:event_bcleaeActionPerformed

    private void MenupersegiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenupersegiActionPerformed
        // TODO add your handling code here:
        PanelContainer.removeAll();
        PanelContainer.repaint();
        PanelContainer.revalidate();
        
        PanelContainer.add(PanelPersegi);
        PanelContainer.repaint();
        PanelContainer.revalidate();
    }//GEN-LAST:event_MenupersegiActionPerformed

    private void bluasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bluasActionPerformed
        // TODO add your handling code here:
        sisipersegi = Integer.parseInt(sisi.getText());
        luas = sisipersegi * sisipersegi;
        String luaspersegi = Integer.toString(luas);
        
        output.setText(luaspersegi);
        jLabel15.setVisible(true);
        jLabel16.setVisible(true);
        jLabel17.setVisible(true);
        jLabel18.setVisible(true);
        jLabel11.setVisible(true);
    }//GEN-LAST:event_bluasActionPerformed

    private void menupersegipanjangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menupersegipanjangActionPerformed
        // TODO add your handling code here:
        PanelContainer.removeAll();
        PanelContainer.repaint();
        PanelContainer.revalidate();
        
        PanelContainer.add(PanelPersegiPanjang);
        PanelContainer.repaint();
        PanelContainer.revalidate();
    }//GEN-LAST:event_menupersegipanjangActionPerformed

    private void btnkelilingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkelilingActionPerformed
        // TODO add your handling code here:
        
         String buttonText = btnkeliling.getText();
         
        // Melakukan percabangan berdasarkan teks tombol
        if (buttonText.equals("Keliling")) {
          btnkeliling.setText("Clear");
          panjang1 = Integer.parseInt(p.getText());
          lebar1 = Integer.parseInt(l.getText());
          
          kelilingpp = 2 * (panjang1 + lebar1);
          
          outputtext.setText(Integer.toString(kelilingpp));
          
        } else if(buttonText.equals("Clear")){
           btnkeliling.setText("Keliling");
           outputtext.setText("");
           p.setText("");
           l.setText("");
        }
        else{
            btnkeliling.setText("Keliling");
        }
    }//GEN-LAST:event_btnkelilingActionPerformed

        
    private void btnluasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnluasActionPerformed
        // TODO add your handling code here:
        
        String buttonText = btnluas.getText();

        // Melakukan percabangan berdasarkan teks tombol
        if (buttonText.equals("Luas")) {
          btnluas.setText("Clear");
          panjang1 = Integer.parseInt(p.getText());
          lebar1 = Integer.parseInt(l.getText());
          
          luaspp = panjang1 * lebar1;
          
          outputtext.setText(Integer.toString(luaspp));
          
        } else if(buttonText.equals("Clear")){
           btnluas.setText("Luas");
           outputtext.setText("");
           p.setText("");
           l.setText("");
        }
        else{
            btnluas.setText("Luas");
        }
    }//GEN-LAST:event_btnluasActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        // TODO add your handling code here:
        PanelContainer.removeAll();
        PanelContainer.repaint();
        PanelContainer.revalidate();
        
        PanelContainer.add(PanelMenu);
        PanelContainer.repaint();
        PanelContainer.revalidate();
    }//GEN-LAST:event_btnbackActionPerformed

    private void btnkellingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkellingActionPerformed
        // TODO add your handling code here:
        String buttonText = btnkelling.getText();

        // Melakukan percabangan berdasarkan teks tombol
        if (buttonText.equals("Keliling")) {
          btnkelling.setText("Clear");
          jari1 = Integer.parseInt(jari2.getText());
          
          kelilinglingkaran = (int) (2* Math.PI * jari1);
          
          outputling.setText(Integer.toString(kelilinglingkaran));
          
        } else if(buttonText.equals("Clear")){
           btnkelling.setText("Keliling");
           outputling.setText("");
           jari2.setText("");
        }
        else{
            btnluasling.setText("Keliling");
        }
        
    }//GEN-LAST:event_btnkellingActionPerformed

    private void btnluaslingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnluaslingActionPerformed
        // TODO add your handling code here:
        String buttonText = btnluasling.getText();

        // Melakukan percabangan berdasarkan teks tombol
        if (buttonText.equals("Luas")) {
          btnluasling.setText("Clear");
          jari1 = Integer.parseInt(jari2.getText());
          
          luaslingkaran = (int) Math.PI * jari1 * jari1;
          
          outputling.setText(Integer.toString(luaslingkaran));
          
        } else if(buttonText.equals("Clear")){
           btnluasling.setText("Luas");
           outputling.setText("");
           jari2.setText("");
        }
        else{
            btnluasling.setText("Luas");
        }
        
    }//GEN-LAST:event_btnluaslingActionPerformed

    private void btnbacklingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbacklingActionPerformed
        // TODO add your handling code here:
        PanelContainer.removeAll();
        PanelContainer.repaint();
        PanelContainer.revalidate();
        
        PanelContainer.add(PanelMenu);
        PanelContainer.repaint();
        PanelContainer.revalidate();
    }//GEN-LAST:event_btnbacklingActionPerformed

    private void jari2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jari2ActionPerformed
    }//GEN-LAST:event_jari2ActionPerformed

    private void MenulingkaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenulingkaranActionPerformed
        // TODO add your handling code here:
        PanelContainer.removeAll();
        PanelContainer.repaint();
        PanelContainer.revalidate();
        
        PanelContainer.add(PanelLingkaran);
        PanelContainer.repaint();
        PanelContainer.revalidate();
    }//GEN-LAST:event_MenulingkaranActionPerformed

    private void btnkelilingsegiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkelilingsegiActionPerformed
        // TODO add your handling code here:\
        String buttonText = btnkelilingsegi.getText();

        // Melakukan percabangan berdasarkan teks tombol
        if (buttonText.equals("Keliling")) {
          btnkelilingsegi.setText("Clear");
          nilaia = Integer.parseInt(A.getText());
          nilaib = Integer.parseInt(B.getText());
          double nilaic = Math.pow(nilaia,2) + Math.pow(nilaib,2);
          int nilaic2 = (int) nilaic;
          kelilingsegi = nilaia + nilaib + nilaic2;
          
          outputsegitiga.setText(Integer.toString(kelilingsegi));
          
        } else if(buttonText.equals("Clear")){
           btnkelilingsegi.setText("Keliling");
           outputsegitiga.setText("");
           A.setText("");
           B.setText("");
        }
        else{
            btnkelilingsegi.setText("Keliling");
        }
    }//GEN-LAST:event_btnkelilingsegiActionPerformed

    private void btnluassegiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnluassegiActionPerformed
        // TODO add your handling code here:
        
        String buttonText = btnluassegi.getText();

        // Melakukan percabangan berdasarkan teks tombol
        if (buttonText.equals("Luas")) {
          btnluassegi.setText("Clear");
          nilaia = Integer.parseInt(A.getText());
          nilaib = Integer.parseInt(B.getText());
          
          luassegi = (nilaia * nilaib)/2;
          
          outputsegitiga.setText(Integer.toString(luassegi));
          
        } else if(buttonText.equals("Clear")){
           btnluassegi.setText("Luas");
           outputsegitiga.setText("");
           A.setText("");
           B.setText("");
        }
        else{
            btnluassegi.setText("Luas");
        }
    }//GEN-LAST:event_btnluassegiActionPerformed

    private void btnbacksegiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbacksegiActionPerformed
        // TODO add your handling code here:
        PanelContainer.removeAll();
        PanelContainer.repaint();
        PanelContainer.revalidate();
        
        PanelContainer.add(PanelMenu);
        PanelContainer.repaint();
        PanelContainer.revalidate();
    }//GEN-LAST:event_btnbacksegiActionPerformed

    private void MenusegitigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenusegitigaActionPerformed
        // TODO add your handling code here:
        PanelContainer.removeAll();
        PanelContainer.repaint();
        PanelContainer.revalidate();
        
        PanelContainer.add(PanelSegitiga);
        PanelContainer.repaint();
        PanelContainer.revalidate();
        
    }//GEN-LAST:event_MenusegitigaActionPerformed

    private void btnkelilingjajarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkelilingjajarActionPerformed
        // TODO add your handling code here:
        String buttonText = btnkelilingjajar.getText();

        // Melakukan percabangan berdasarkan teks tombol
        if (buttonText.equals("Keliling")) {
          btnkelilingjajar.setText("Clear");
          alas1 = Integer.parseInt(alas.getText());
          tinggi1 = Integer.parseInt(tinggi.getText());
          
          kelilingjajar =  2 * (alas1 + tinggi1);
          
          outputjajar.setText(Integer.toString(kelilingjajar));
          
        } else if(buttonText.equals("Clear")){
           btnkelilingjajar.setText("Keliling");
           outputjajar.setText("");
           alas.setText("");
           tinggi.setText("");
        }
        else{
            btnkelilingjajar.setText("Keliling");
        }
        
    }//GEN-LAST:event_btnkelilingjajarActionPerformed

    private void btnluasjajarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnluasjajarActionPerformed
        // TODO add your handling code here:
        String buttonText = btnluasjajar.getText();

        // Melakukan percabangan berdasarkan teks tombol
        if (buttonText.equals("Luas")) {
          btnluasjajar.setText("Clear");
          alas1 = Integer.parseInt(alas.getText());
          tinggi1 = Integer.parseInt(tinggi.getText());
          
          luasjajar = alas1 * tinggi1;
          
          outputjajar.setText(Integer.toString(luasjajar));
          
        } else if(buttonText.equals("Clear")){
           btnluasjajar.setText("Luas");
           outputjajar.setText("");
           alas.setText("");
           tinggi.setText("");
        }
        else{
            btnluasjajar.setText("Luas");
        }
    }//GEN-LAST:event_btnluasjajarActionPerformed

    private void btnbackjajarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackjajarActionPerformed
        // TODO add your handling code here:
        PanelContainer.removeAll();
        PanelContainer.repaint();
        PanelContainer.revalidate();
        
        PanelContainer.add(PanelMenu);
        PanelContainer.repaint();
        PanelContainer.revalidate();
    }//GEN-LAST:event_btnbackjajarActionPerformed

    private void MenujajargenjangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenujajargenjangActionPerformed
        // TODO add your handling code here:
        PanelContainer.removeAll();
        PanelContainer.repaint();
        PanelContainer.revalidate();
        
        PanelContainer.add(PanelJajarGenjang);
        PanelContainer.repaint();
        PanelContainer.revalidate();
    }//GEN-LAST:event_MenujajargenjangActionPerformed

    private void MenubelahketupatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenubelahketupatActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Mohon maaf menu belah ketupat masih maintance.", "Pemberitahuan",  JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_MenubelahketupatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kakulator_bangundatar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kakulator_bangundatar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kakulator_bangundatar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kakulator_bangundatar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kakulator_bangundatar().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField A;
    private javax.swing.JTextField B;
    private javax.swing.JButton Bback;
    private javax.swing.JButton Bhome;
    private javax.swing.JButton Bmenu;
    private javax.swing.JButton Menubelahketupat;
    private javax.swing.JButton Menujajargenjang;
    private javax.swing.JButton Menulingkaran;
    private javax.swing.JButton Menupersegi;
    private javax.swing.JButton Menusegitiga;
    private javax.swing.JPanel PanelContainer;
    private javax.swing.JPanel PanelHome;
    private javax.swing.JPanel PanelJajarGenjang;
    private javax.swing.JPanel PanelLingkaran;
    private javax.swing.JPanel PanelMenu;
    private javax.swing.JPanel PanelPersegi;
    private javax.swing.JPanel PanelPersegiPanjang;
    private javax.swing.JPanel PanelSegitiga;
    private javax.swing.JPanel PanelSidebar;
    private javax.swing.JTextField alas;
    private javax.swing.JButton bcleae;
    private javax.swing.JButton bkeliling;
    private javax.swing.JButton bluas;
    private javax.swing.JButton btnback;
    private javax.swing.JButton btnbackjajar;
    private javax.swing.JButton btnbackling;
    private javax.swing.JButton btnbacksegi;
    private javax.swing.JButton btnkeliling;
    private javax.swing.JButton btnkelilingjajar;
    private javax.swing.JButton btnkelilingsegi;
    private javax.swing.JButton btnkelling;
    private javax.swing.JButton btnluas;
    private javax.swing.JButton btnluasjajar;
    private javax.swing.JButton btnluasling;
    private javax.swing.JButton btnluassegi;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTextField jari2;
    private javax.swing.JTextField l;
    private javax.swing.JButton menupersegipanjang;
    private javax.swing.JLabel output;
    private javax.swing.JLabel outputjajar;
    private javax.swing.JLabel outputling;
    private javax.swing.JLabel outputsegitiga;
    private javax.swing.JLabel outputtext;
    private javax.swing.JTextField p;
    private javax.swing.JTextField sisi;
    private javax.swing.JTextField tinggi;
    // End of variables declaration//GEN-END:variables

}
